### ISSUE TITLE
Investigate pokedex APIs for getting minimum required response

### ISSUE THREAD

**Issue by arhsimluhar** [Bandana9Singh/pokedex-react#7]
Right now, Pokedex API being is sending a lot of other unnecessary information when only image and pokemon name is required on homepage, this is a spike issue to check if there exists an API that provides this minimum information so that we can reduce the data being sent over the internet.

**Comment by abtoma** [comment]
i dont think we have access to their api structure and i dont think the backend api is on graphql then we could have done it
